import { Keyword } from '../types'

interface Topics {
  [index: string]: string[]
}

export const topics: Topics = {
  greeting: [
    'hi',
    'hello',
    'hey',
    'sup',
    'who',
    'greetings',
    'morning',
    'evening',
    'help',
  ],
  skills: [
    'skills',
    'stack',
    'react',
    'node',
    'typescript',
    'supabase',
    'frontend',
    'backend',
    'technologies',
    'languages',
    'tools',
    'frameworks',
    'css',
    'tailwind',
    'state',
    'management',
  ],
  databases: [
    'database',
    'postgres',
    'postgresql',
    'sql',
    'prisma',
    'orm',
    'nosql',
    'query',
    'migration',
  ],
  testing: [
    'testing',
    'test',
    'jest',
    'cypress',
    'playwright',
    'tdd',
    'qa',
    'unit',
  ],
  git_devops: [
    'git',
    'github',
    'ci',
    'cd',
    'actions',
    'vercel',
    'deploy',
    'deployment',
    'docker',
    'hosting',
  ],
  experience: [
    'experience',
    'projects',
    'built',
    'work',
    'resume',
    'portfolio',
    'background',
    'history',
    'code',
    'apps',
    'past',
    'companies',
  ],
  soft_skills: [
    'team',
    'agile',
    'scrum',
    'communication',
    'culture',
    'remote',
    'collaborate',
    'lead',
  ],
  career_goals: [
    'goals',
    'future',
    'learn',
    'learning',
    'next',
    'direction',
    'ambition',
  ],
  contact: [
    'contact',
    'email',
    'hire',
    'linkedin',
    'job',
    'freelance',
    'remote',
    'reach',
    'call',
    'schedule',
    'phone',
  ],
  fun_meta: [
    'source',
    'how',
    'bot',
    'built',
    'ai',
    'joke',
    'favorite',
    'coffee',
    'dark',
    'light',
  ],
}

export const keywords: Keyword = {
  greeting: {
    g0: ['hi hello hey there', 'hi there friendly greeting', 'yo what is up'],
    g1: ['how is it going', 'how are you doing', 'how have you been today'],
    g2: [
      'who are you',
      'what is this website',
      'tell me about yourself',
      'what do you do',
    ],
    g3: [
      'what can i ask you',
      'help me with options',
      'what commands do you support',
    ],
    nope: [
      'nothing',
      'bye',
      'stop',
      'goodbye',
      'quit',
      'exit chat',
      'end conversation',
    ],
  },
  skills: {
    s0: [
      'what is your frontend stack',
      'what frontend tools do you use',
      'tell me about your frontend skills',
      'what frontend frameworks do you prefer',
    ],
    s1: [
      'what is your backend stack',
      'tell me about your backend skills',
      'what backend technologies do you write',
      'what do you use for server logic',
    ],
    s2: [
      'what are your skills',
      'what skills do you have',
      'list your general skills',
      'what are you good at',
    ],
    s3: [
      'what is your tech stack',
      'what is your core stack',
      'what technologies do you use daily',
      'what is your main technology stack',
    ],
    s4: [
      'what programming languages do you know',
      'what languages do you speak code',
      'what languages do you write',
    ],
    s5: [
      'what styling tools do you use',
      'do you use tailwind css',
      'how do you style your applications',
      'do you know material ui',
    ],
    s6: [
      'how do you handle global state management',
      'do you use redux',
      'do you know zustand',
      'how do you pass state in react',
    ],
    s7: [
      'do you write typescript',
      'why do you use typescript',
      'is your code strongly typed',
    ],
    s8: [
      'do you know react',
      'tell me about your react experience',
      'how long have you used react',
    ],
    s9: [
      'do you know next.js',
      'why do you choose nextjs',
      'tell me about your nextjs architecture skills',
    ],
  },
  databases: {
    d0: [
      'what databases do you use',
      'are you familiar with relational databases',
      'do you use sql',
    ],
    d1: [
      'do you know supabase',
      'have you used supabase authentication',
      'tell me about your supabase experience',
    ],
    d2: [
      'do you write raw postgresql queries',
      'what is your postgres experience',
      'do you know postgres',
    ],
    d3: ['do you use an orm', 'have you used prisma', 'do you use mongoose'],
    d4: [
      'do you know nosql',
      'have you used mongodb',
      'do you use redis for caching',
    ],
  },
  testing: {
    t0: [
      'do you write tests',
      'what is your testing strategy',
      'do you do automated testing',
    ],
    t1: [
      'do you know jest',
      'have you done unit testing with jest',
      'do you use react testing library',
    ],
    t2: [
      'do you know cypress',
      'have you written end to end tests',
      'do you use playwright for e2e',
    ],
    t3: [
      'what is your opinion on tdd',
      'do you practice test driven development',
    ],
  },
  git_devops: {
    v0: [
      'how do you deploy your applications',
      'do you use vercel',
      'where do you host your fullstack projects',
    ],
    v1: [
      'what is your git workflow',
      'how do you handle branches in git',
      'do you use github flow',
    ],
    v2: [
      'do you know ci cd',
      'have you built github actions pipelines',
      'do you automate deployments',
    ],
    v3: [
      'do you know docker',
      'have you containerized microservices with docker',
      'do you use containers',
    ],
  },
  experience: {
    e0: [
      'what have you built',
      'show me your projects',
      'what projects have you done',
      'do you have live project examples',
    ],
    e1: [
      'what is your experience',
      'tell me about your work history',
      'where have you worked',
      'show me your background',
    ],
    e2: [
      'can i see your resume',
      'download your cv',
      'do you have a resume file',
      'where is your resume',
    ],
    e3: [
      'show me your github',
      'what is your github profile',
      'do you open source your code',
    ],
    e4: [
      'have you worked in a professional engineering team',
      'what is your corporate experience',
      'have you worked with production codebases',
    ],
    e5: [
      'what is the most complex app you built',
      'tell me about your best project',
      'what project are you most proud of',
    ],
    e6: [
      'have you ever broken production',
      'tell me about a time you failed',
      'how do you handle production bugs',
    ],
  },
  soft_skills: {
    m0: [
      'how do you handle remote communication',
      'are you good at working asynchronously',
      'how do you stay productive remotely',
    ],
    m1: [
      'are you familiar with agile methodology',
      'have you worked in scrum teams',
      'do you participate in daily standups',
    ],
    m2: [
      'how do you handle code reviews',
      'how do you give feedback to other developers',
      'what is your approach to collaboration',
    ],
    m3: [
      'can you lead projects',
      'have you mentored junior developers',
      'what is your leadership style',
    ],
  },
  career_goals: {
    l0: [
      'what are you learning right now',
      'what new technology are you exploring',
      'what is on your learning roadmap',
    ],
    l1: [
      'where do you see yourself in five years',
      'what are your career goals',
      'what is your ultimate tech ambition',
    ],
    l2: [
      'what fields of software engineering interest you most',
      'are you interested in ai engineering',
      'do you want to learn devops deep dive',
    ],
  },
  contact: {
    c0: [
      'how can i contact you',
      'what is your email',
      'how do i reach you email me',
    ],
    c1: [
      'give me your linkedin',
      'what is your linkedin profile',
      'are you on linkedin',
    ],
    c2: [
      'are you available for work',
      'are you looking for a job',
      'are you open to remote work',
      'are you seeking full-time positions',
    ],
    c3: [
      'do you do freelance',
      'are you taking freelance gigs',
      'what is your freelance availability',
    ],
    c4: [
      'can we schedule an interview phone call',
      'how do i book a meeting with you',
      'do you have a calendly link',
    ],
    c5: [
      'where do you live location',
      'where are you located physically',
      'what timezone are you in',
    ],
  },
  fun_meta: {
    f0: [
      'how did you build this chatbot simulator',
      'what is the engine behind this chat',
      'is this real artificial intelligence or an open ai wrapper',
    ],
    f1: ['can you tell me a joke', 'make me laugh software engineer joke'],
    f2: [
      'do you prefer dark mode or light mode',
      'what is your favorite theme color preference',
    ],
    f3: [
      'how much coffee do you drink',
      'are you fueled by caffeine',
      'what is your favorite programming beverage',
    ],
    f4: [
      'where is the source code for this portfolio website',
      'can i copy this engine code repository',
    ],
  },
}
